### ISSUE TITLE
ffmpeg is a dependency, but is not listed in install instructions or installed automatically

### ISSUE THREAD

**Issue by hcphoenix** [Splendide-Imaginarius/crosslooper#1]
Installed through `pyenv exec pip install .` using python version 3.12.4 on Debian 12.  Errors out on trying to modify a .ogg file if ffmpeg isn't installed, but works fine if ffmpeg is installed through apt.

```
Traceback (most recent call last):
  File "/home/cadence/.local/bin/crosslooper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cadence/.local/lib/python3.12/site-packages/crosslooper.py", line 348, in file_offset
    sample_rate, s1, s2 = read_normalized(in1, in2)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cadence/.local/lib/python3.12/site-packages/crosslooper.py", line 123, in read_normalized
    r1, s1 = normalize_denoise(in1, 'out1')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cadence/.local/lib/python3.12/site-packages/crosslooper.py", line 72, in normalize_denoise
    in_out(ffmpegwav if (take is None or not allow_take) else ffmpegwavtake, infile, outfile)
  File "/home/cadence/.local/lib/python3.12/site-packages/crosslooper.py", line 63, in in_out
    subprocess.run(command,
  File "/home/cadence/.pyenv/versions/3.12.4/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cadence/.pyenv/versions/3.12.4/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/cadence/.pyenv/versions/3.12.4/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```

**Comment by hcphoenix** [comment]
Oh this is me not using the pyenv right isn't it. It's insisting on 3.12 when executing. I'll just run from Windows rather than fighting Debian on this.

**Comment by hcphoenix** [comment]
Closed on accident. Need to not use Github at 4 AM.

**Comment by Splendide-Imaginarius** [comment]
Thanks for the report!
